# Generated by Django 4.2.21 on 2025-05-14 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemReport',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reports/photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('road', 'Route endommagée'), ('electricity', 'Panne électrique'), ('waste', 'Déchets sauvages'), ('sanitation', "Problème d'assainissement"), ('other', 'Autre incident')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('resolved', 'Résolu')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
