# Generated by Django 4.2.21 on 2025-05-14 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_remove_route_distance_remove_route_end_point_and_more'),
        ('reports', '0003_comment_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='navigation.route'),
        ),
    ]
