# Generated by Django 4.2.21 on 2025-05-14 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='route',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_point',
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='route',
            name='end_latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='end_longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
